apiVersion: v1
kind: Pod
metadata:
  name: serverweb1
  labels:
    app: frontend
    env: dev
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: serverweb2
  labels:
    app: backend
    env: dev
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
