apiVersion: v1
kind: Secret
metadata:
  name: connectionstring
type: Opaque
stringData:
  host: localhost
  username: administrator
  password: "12345"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: desploy-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: connectionstring
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: connectionstring
                  key: username
